[tool.black]
line-length = 100
target_version = ['py310', 'py311']
skip-string-normalization = true

[build-system]
requires = ["setuptools", "wheel", "Cython"]


[tool.pytest.ini_options]
testpaths = [
    "test",
    "test_perf",
]
markers = [
    "cirq: mark a test as a compatibility test with Cirq.",
]
addopts = '-m "not cirq"'
